/**
 * Styles that came from somewhere else: the registry format, and how a manifest
 * somebody on the internet wrote becomes something kururu will draw.
 *
 * `../kururu-styles` is the sibling repository this talks to — themes, skins,
 * mascots and packs as data, an `index.json` generated by its CI, fetched over
 * HTTPS by the **server** and installed into `~/.config/kururu/styles`. Its
 * README is the specification and its `AGENTS.md` is the brief for anybody
 * adding to it; what is in here is only kururu's half, which is the fetching,
 * the checking and the adopting.
 *
 * ## Why installing is a copy and not a link
 *
 * Three reasons and each is sufficient on its own. A style that changed under
 * you mid-session would be a window that redrew itself while you were reading
 * it. Kururu has to work with no network, because a machine on a plane and a
 * GitHub outage are the same case and in both of them the window still has to
 * come up. And *check for updates* only means something if there is a pinned
 * version to compare against — a style that is always the latest cannot tell you
 * that it changed, which is the whole feature.
 *
 * So an update is always something somebody pressed, and what is on disk is a
 * copy with a version and a digest recorded beside it.
 *
 * ## Why a theme is complete and a skin is a difference
 *
 * The one asymmetry in the format, and it looks like an inconsistency until you
 * try the other arrangement.
 *
 * A **skin** is merged onto `BASE_TOKENS`, so it writes only what it moves. The
 * tokens compose: a skin that says "square corners" and nothing else genuinely
 * means *kururu, with square corners*, and it should inherit an elevation
 * shadow kururu improves later. A skin written out in full would silently keep
 * whatever the base said the day it was written.
 *
 * A **theme** is complete, every token, no merge — because a palette does not
 * compose. A Dracula missing `blocked` would draw Catppuccin's yellow: a colour
 * from a different palette, chosen against a different ground, and near enough
 * right that nobody would ever file it. What you would have is a theme that is
 * *nearly* the thing on the tin, which is precisely what a port must not be.
 *
 * Forward compatibility is then handled at this end instead: `adoptTheme` fills
 * a missing token from the default theme rather than refusing the file. That is
 * `adopt()` in `workspaces.ts` doing the same job for the same reason — a
 * manifest written against an older token set is exactly the case a registry
 * guarantees will happen, and refusing it would mean every entry dying the day
 * kururu grows a token.
 *
 * ## Everything in here is hostile input
 *
 * A manifest is a file somebody else wrote, fetched over the network, that ends
 * up as custom properties on the root element of a window reachable from the
 * tailnet — and, for a mascot, as a PNG written into the user's config
 * directory. So this module is mostly checking, and the checks are the ones
 * `files.ts` and `set-workspace-color` already argue for: a name that becomes a
 * path is checked against a list, a number is clamped to the nearest legal
 * value, and an enumeration falls back. The one rule with no give in it is that
 * **nothing may name a URL**: `cssValue` below refuses anything that would make
 * the window fetch from a host it did not choose, because a window that phones
 * out while it paints tells whoever answers when its owner is working.
 */
import { adoptMascot, type MascotConfig } from "./model";
import {
  BASE_ICONS,
  ICON_NAMES,
  isPartName,
  isStyleId,
  PAINT_MODES,
  PAINT_REPEATS,
  PART_NAMES,
  type IconName,
  type IconSheet,
  type PaintMode,
  type PaintRepeat,
  type PartName,
  type PartPaint,
  type Skin,
  type SkinFont,
  type SkinTokens,
} from "./skin";
import { skinFor } from "./skin";
import type { Theme, TerminalTokens, UiTokens, WorkspaceColorName } from "./theme";
import { adoptFontFamily, themeFor } from "./theme";

/** The schema this version of kururu speaks. An index declaring another is not for us. */
export const STYLES_SCHEMA = 1;

export type StyleKind = "theme" | "skin" | "mascot" | "sound" | "pack";

export const STYLE_KINDS: readonly StyleKind[] = ["theme", "skin", "mascot", "sound", "pack"];

export function isStyleKind(value: unknown): value is StyleKind {
  return STYLE_KINDS.includes(value as StyleKind);
}

/** `major.minor.patch`, and nothing else. No pre-release tags; see the registry README. */
export function isVersion(value: unknown): value is string {
  return typeof value === "string" && /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(value);
}

/**
 * `1.2.0` against `1.10.0`, numerically rather than as strings.
 *
 * The string comparison is the classic bug and it is silent in exactly the wrong
 * direction: `"1.10.0" < "1.2.0"` is true, so a real update reads as a downgrade
 * and the row says you are current forever.
 */
export function compareVersions(a: string, b: string): number {
  const x = a.split(".").map(Number);
  const y = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    const d = (x[i] ?? 0) - (y[i] ?? 0);
    if (d !== 0) return d;
  }
  return 0;
}

// ---------------------------------------------------------------------------
// The index
// ---------------------------------------------------------------------------

export interface StyleFile {
  name: string;
  size: number;
  /** `sha256-<hex>`, over this file alone. */
  digest: string;
}

/**
 * One entry as `index.json` describes it — everything needed to list it, and
 * everything needed to fetch it, but not the manifest itself.
 *
 * The manifest is one request away and is only wanted by an install, whereas
 * this list is drawn every time somebody opens the tab. `preview` is the
 * compromise: the handful of values Settings needs to draw the entry *in itself*
 * rather than as a name, which is the same argument kururu's own theme picker
 * already makes about its swatches.
 */
export interface StyleEntry {
  kind: StyleKind;
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  licence: string;
  homepage?: string;
  source?: string;
  /** Where the entry's directory is, relative to the registry root. */
  path: string;
  /** The manifest's file name inside it. */
  manifest: string;
  /** `sha256-<hex>` over the whole entry — names and contents. */
  digest: string;
  files: StyleFile[];
  preview: StylePreview;
}

/**
 * What a row can be drawn from before anything is installed.
 *
 * Deliberately `unknown`-ish per kind rather than four exact interfaces: it is
 * read only by the component that draws that kind of card, every field of it is
 * optional by nature (a skin that changes no radius has no radius to preview),
 * and a strict shape here would mean a registry that could not add a preview
 * field without every older kururu refusing the index.
 */
export type StylePreview = Record<string, unknown>;

export interface StyleIndex {
  schema: number;
  entries: StyleEntry[];
}

/**
 * Whatever came back from the registry, as something that can be listed.
 *
 * Entries that do not survive are dropped rather than failing the whole fetch,
 * because the alternative is one malformed contribution taking the tab down for
 * everybody until somebody notices. A wrong *schema* does fail, and that is the
 * one case where refusing is right: it means this kururu and that registry
 * disagree about what a manifest is, and a partial reading of a format you do
 * not speak is worse than saying so.
 */
export function adoptIndex(value: unknown): StyleIndex | null {
  const raw = value as { schema?: unknown; entries?: unknown };
  if (!raw || typeof raw !== "object") return null;
  if (raw.schema !== STYLES_SCHEMA) return null;
  if (!Array.isArray(raw.entries)) return null;
  const entries: StyleEntry[] = [];
  for (const one of raw.entries) {
    const e = adoptEntry(one);
    if (e) entries.push(e);
  }
  return { schema: STYLES_SCHEMA, entries };
}

function adoptEntry(value: unknown): StyleEntry | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isStyleKind(raw.kind) || !isStyleId(raw.id) || !isVersion(raw.version)) return null;
  if (!isDigest(raw.digest)) return null;
  /**
   * `path` and `manifest` become URL segments and then file names on disk, so
   * they are rebuilt from the kind and the id rather than taken. An index that
   * disagrees with the layout is an index we do not follow off it — this is the
   * `files.ts` rule about never learning a root from a client, applied to the
   * one place a *file* could learn one.
   */
  const files: StyleFile[] = [];
  for (const f of Array.isArray(raw.files) ? raw.files : []) {
    const one = f as Record<string, unknown>;
    if (!isAssetName(one.name) || !isDigest(one.digest)) return null;
    files.push({ name: one.name, size: typeof one.size === "number" ? one.size : 0, digest: one.digest });
  }
  if (files.length === 0) return null;
  return {
    kind: raw.kind,
    id: raw.id,
    name: line(raw.name) || raw.id,
    version: raw.version,
    description: line(raw.description),
    author: line(raw.author),
    licence: line(raw.licence),
    ...(typeof raw.homepage === "string" && isHttps(raw.homepage) ? { homepage: raw.homepage } : {}),
    ...(typeof raw.source === "string" && isHttps(raw.source) ? { source: raw.source } : {}),
    path: `${raw.kind}s/${raw.id}`,
    manifest: `${raw.kind}.json`,
    digest: raw.digest,
    files,
    preview: (raw.preview && typeof raw.preview === "object" ? raw.preview : {}) as StylePreview,
  };
}

function isDigest(value: unknown): value is string {
  return typeof value === "string" && /^sha256-[0-9a-f]{64}$/.test(value);
}

/**
 * A file inside an entry. A name, never a path: it is joined onto a directory on
 * both ends of the transfer, and `..` is the whole of why `files.ts` exists.
 * Nested directories are refused rather than supported — no entry needs one, and
 * "no slashes" is a rule that cannot be got wrong.
 */
export function isAssetName(value: unknown): value is string {
  return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(value) && !value.includes("..");
}

function isHttps(value: string): boolean {
  return /^https:\/\/[^\s"'<>]+$/.test(value);
}

/** One line of somebody else's prose, on its way into the window's chrome. */
function line(value: unknown): string {
  return typeof value === "string" ? value.replace(/[\r\n]+/g, " ").trim().slice(0, 200) : "";
}

// ---------------------------------------------------------------------------
// What is on disk
// ---------------------------------------------------------------------------

/**
 * One installed style, as `installed.json` records it.
 *
 * The version and the digest are the pin, and they answer different questions.
 * The **version** is what "update available" is computed from — it is a sentence
 * for a person, which a hash is not. The **digest** is what says the bytes on
 * disk are the bytes the registry has, which is npm's `integrity` field doing
 * npm's job; the failure it catches is the dull one, a download cut in half over
 * a phone connection leaving a torn sprite sheet in a config directory.
 *
 * `sheet` and `mascotId` are a mascot's only, and they exist because installing
 * a mascot is the one kind that writes somewhere else as well: the sheet goes
 * into `~/.config/kururu/sheets`, where the picker already looks, and an entry
 * goes into the mascot list. Remembering both is what lets an uninstall undo
 * exactly what an install did, rather than guessing from a name.
 */
export interface InstalledStyle {
  kind: StyleKind;
  id: string;
  name: string;
  version: string;
  digest: string;
  /** ISO 8601, so a list can be sorted by when somebody got it. */
  installedAt: string;
  files: string[];
  sheet?: string;
  mascotId?: string;
  /**
   * Made here, in the studio, rather than fetched from the registry. The one
   * distinction the rest of kururu is allowed to draw between the two: the
   * catalogue does not offer to update it, `install` refuses to overwrite it,
   * and the studio lists it. Everything else — serving, wearing, removing —
   * treats it as any other installed skin, which is the point of storing it
   * as one.
   */
  local?: boolean;
}

export function adoptInstalled(value: unknown): InstalledStyle[] {
  if (!Array.isArray(value)) return [];
  const out: InstalledStyle[] = [];
  for (const one of value) {
    const raw = (one ?? {}) as Record<string, unknown>;
    if (!isStyleKind(raw.kind) || !isStyleId(raw.id) || !isVersion(raw.version)) continue;
    if (!isDigest(raw.digest)) continue;
    out.push({
      kind: raw.kind,
      id: raw.id,
      name: line(raw.name) || raw.id,
      version: raw.version,
      digest: raw.digest,
      installedAt: typeof raw.installedAt === "string" ? raw.installedAt : "",
      files: Array.isArray(raw.files) ? raw.files.filter(isAssetName) : [],
      ...(isStyleId(raw.sheet) ? { sheet: raw.sheet } : {}),
      ...(typeof raw.mascotId === "string" ? { mascotId: raw.mascotId } : {}),
      ...(raw.local === true ? { local: true } : {}),
    });
  }
  return out;
}

/**
 * The installed styles a client needs, resolved and ready to draw.
 *
 * Resolved on the server rather than sent as manifests, because adopting is
 * checking and the checking has to happen once, on the side that also has to
 * write the files. A client is then handed the same `Theme` and `Skin` shapes
 * the built-ins already are, and every list in the window is one concatenation.
 */
export interface StyleLibrary {
  themes: Theme[];
  skins: Skin[];
  /** Every installed entry of every kind, including mascots and packs. */
  installed: InstalledStyle[];
}

export const EMPTY_LIBRARY: StyleLibrary = { themes: [], skins: [], installed: [] };

// ---------------------------------------------------------------------------
// Manifests
// ---------------------------------------------------------------------------

/**
 * A CSS value from a manifest, or null if it is one we will not write.
 *
 * The check is narrow on purpose and there is exactly one thing it is really
 * about: **nothing may make the window fetch from a host it did not choose.** A
 * `url()` naming a scheme, a protocol-relative `//`, an `@import` — each of
 * those turns a border into a beacon that fires every time somebody's window
 * paints, and kururu is a window that is open all day. A skin *may* reference
 * its own shipped file, and by the time a value reaches here the server has
 * already rewritten `url(paper.png)` into kururu's own asset endpoint, so any
 * surviving `url(` that does not point there is one we did not put in.
 *
 * The rest is belt and braces. These values go through `setProperty`, which
 * parses and silently drops what it cannot use rather than splicing text into a
 * stylesheet, so a value ending a declaration early is not the hole it would be
 * in a template. Refusing the characters anyway costs nothing and means the one
 * place a stranger's string meets the root element is not also the place we are
 * relying on a browser behaving well.
 */
export function cssValue(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const v = value.trim();
  if (!v || v.length > 400) return null;
  if (/[;{}<>\\]/.test(v)) return null;
  if (/@import|expression\s*\(|javascript:|<\/?script/i.test(v)) return null;
  for (const m of v.matchAll(/url\(\s*['"]?([^'")]*)/gi)) {
    if (!m[1]!.startsWith(ASSET_PATH)) return null;
  }
  if (/:\/\//.test(v)) return null;
  return v;
}

/**
 * The one URL shape a style's own files are ever served at.
 *
 * A constant rather than a string spelled in three files, because both halves of
 * the `cssValue` check above — the server writing the rewrite and this refusing
 * anything else — have to mean the same prefix or the check is decoration.
 */
export const ASSET_PATH = "/api/styles/asset";

/**
 * A theme manifest, made into a `Theme`.
 *
 * Every token is required *of the author* and filled in from `base` when it is
 * missing anyway — see the header for why those are not contradictory. What is
 * refused outright is a manifest that is not a theme at all: no id, no ui block,
 * nothing to draw.
 */
export function adoptThemeManifest(value: unknown, base: Theme = themeFor(null)): Theme | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isStyleId(raw.id)) return null;
  const ui = raw.ui as Record<string, unknown> | undefined;
  const terminal = raw.terminal as Record<string, unknown> | undefined;
  const workspace = raw.workspace as Record<string, unknown> | undefined;
  if (!ui || typeof ui !== "object") return null;

  const outUi = {} as UiTokens;
  for (const token of Object.keys(base.ui) as (keyof UiTokens)[]) {
    outUi[token] = colour(ui[token]) ?? base.ui[token];
  }
  const outTerminal = {} as TerminalTokens;
  for (const token of Object.keys(base.terminal) as (keyof TerminalTokens)[]) {
    outTerminal[token] = colour(terminal?.[token]) ?? base.terminal[token];
  }
  const outWorkspace = {} as Record<WorkspaceColorName, string>;
  for (const token of Object.keys(base.workspace) as WorkspaceColorName[]) {
    outWorkspace[token] = colour(workspace?.[token]) ?? base.workspace[token];
  }

  return {
    id: raw.id,
    name: line(raw.name) || raw.id,
    appearance: raw.appearance === "light" ? "light" : "dark",
    ui: outUi,
    terminal: outTerminal,
    workspace: outWorkspace,
  };
}

/**
 * A colour, or null.
 *
 * Narrower than `cssValue` and separately spelled, because these do not only
 * reach CSS: every terminal token is handed to ghostty, which paints into a
 * canvas and has its own ideas about what it will parse. A hex or an
 * `rgb()`/`hsl()` function is the intersection of what both sides understand,
 * and a named colour is deliberately not in it — `rebeccapurple` is valid CSS
 * and is not a thing an ANSI palette should be expressed in.
 */
function colour(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const v = value.trim();
  return /^(#[0-9a-fA-F]{3,8}|rgba?\([\d\s.,%/]+\)|hsla?\([\d\s.,%/a-z]+\))$/.test(v) ? v : null;
}

/**
 * A skin manifest, made into a `Skin` by merging onto the built-in base.
 *
 * `asset` turns a file name into a URL kururu serves. It is passed in rather
 * than built here because only the server knows whether a file is actually
 * installed, and a skin naming a font it did not ship should get no `@font-face`
 * rather than a 404 on every paint. `measure` is the same question about a
 * picture — how big is it — which a tile needs answered to be drawn at its
 * scale, and which only the side with the file can answer. Absent, a tile is
 * drawn at its natural size, which is right for one drawn at screen resolution
 * and merely small for pixel art.
 *
 * The parts, the colours and the icon strip are checked the way the tokens are:
 * a value that is not what it claims to be is dropped and the base's answer
 * stands, never the whole manifest refused. The exception is a file name —
 * a part naming a picture the entry did not ship is a part not painted, on the
 * font's reasoning.
 */
export function adoptSkinManifest(
  value: unknown,
  asset: (file: string) => string | null,
  measure: (file: string) => [number, number] | null = () => null,
  /**
   * Keep a skin that moves nothing. Only the studio asks for this, and only
   * for a skin of yours: a new one is the base under your name until you
   * touch something, and the studio has to be able to wear it to show you
   * what touching something does. A registry entry that moves nothing is
   * still refused, since offering it is offering a choice with one outcome.
   */
  lenient = false,
): Skin | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isStyleId(raw.id)) return null;
  const base = skinFor(null);

  const tokens = { ...base.tokens };
  const given = (raw.tokens ?? {}) as Record<string, unknown>;
  let moved = 0;
  for (const token of Object.keys(base.tokens) as (keyof SkinTokens)[]) {
    if (!(token in given)) continue;
    const v = cssValue(given[token]);
    if (v === null) continue;
    tokens[token] = v;
    moved++;
  }

  const icons = { ...BASE_ICONS };
  const glyphs: IconName[] = [];
  const givenIcons = (raw.icons ?? {}) as Record<string, unknown>;
  for (const name of ICON_NAMES) {
    const glyph = givenIcons[name as IconName];
    // `null` is a skin saying it considered this one and kept kururu's, which is
    // the same outcome as leaving it out and is said on purpose. Anything longer
    // than two code points is not a glyph, it is a label.
    if (typeof glyph !== "string") continue;
    const trimmed = glyph.trim();
    if (!trimmed || [...trimmed].length > 2 || /[\r\n\\]/.test(trimmed)) continue;
    icons[name] = trimmed;
    glyphs.push(name);
  }

  const parts: Partial<Record<PartName, PartPaint>> = {};
  const givenParts = (raw.parts ?? {}) as Record<string, unknown>;
  for (const name of PART_NAMES) {
    const paint = adoptPaint(givenParts[name], asset, measure);
    if (!paint) continue;
    parts[name] = paint;
    moved++;
  }

  const colors = adoptColors(raw.colors);
  if (colors) moved++;

  const iconSheet = adoptIconSheet(raw.iconSheet, asset, measure);
  if (iconSheet) moved++;

  // A skin that moved nothing is the default under another name, and offering it
  // is offering a choice with one outcome. A glyph alone counts as nothing moved
  // on purpose: it was never a skin, and it still is not.
  if (moved === 0 && !lenient) return null;

  const fonts: SkinFont[] = [];
  for (const one of Array.isArray(raw.fonts) ? raw.fonts : []) {
    const f = (one ?? {}) as Record<string, unknown>;
    const family = line(f.family);
    if (!family || /["'\\;{}]/.test(family)) continue;
    if (!isAssetName(f.file)) continue;
    const src = asset(f.file);
    if (!src) continue;
    fonts.push({
      family,
      src,
      weight: /^[\d\s]{1,9}$/.test(String(f.weight ?? "")) ? String(f.weight).trim() : "400",
      style: f.style === "italic" ? "italic" : "normal",
    });
  }

  const sheet = isAssetName(raw.stylesheet) ? asset(raw.stylesheet) : null;

  return {
    id: raw.id,
    name: line(raw.name) || raw.id,
    description: line(raw.description),
    tokens,
    icons,
    glyphs,
    parts,
    ...(colors ? { colors } : {}),
    ...(iconSheet ? { iconSheet } : {}),
    ...(fonts.length ? { fonts } : {}),
    ...(sheet ? { stylesheet: sheet } : {}),
  };
}

/**
 * One part's picture, or null if there is nothing to paint.
 *
 * Every number is clamped rather than refused, on the mascot's reasoning: a
 * slice one pixel wider than the picture is a slider dragged too far, and the
 * nearest legal value is the right answer. The file name is the one field that
 * falls back instead of bending, because a name has no nearest legal value —
 * and it is checked twice, as a name and as a file the entry actually has.
 *
 * A slice may be written as one number for all four sides, which is what most
 * bezels are, or as four.
 */
export function adoptPaint(
  value: unknown,
  asset: (file: string) => string | null,
  measure: (file: string) => [number, number] | null,
): PartPaint | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isAssetName(raw.image)) return null;
  const image = asset(raw.image);
  if (!image) return null;
  const mode: PaintMode = PAINT_MODES.includes(raw.mode as PaintMode) ? (raw.mode as PaintMode) : "nine";
  const repeat: PaintRepeat = PAINT_REPEATS.includes(raw.repeat as PaintRepeat) ? (raw.repeat as PaintRepeat) : "stretch";
  const scale = clampInt(raw.scale, 1, 1, 8);
  const size = mode === "tile" ? (measure(raw.image) ?? undefined) : undefined;
  const paint: PartPaint = { image, mode, slice: adoptSlice(raw.slice), scale, repeat };
  if (size) paint.size = size;
  return paint;
}

function adoptSlice(value: unknown): [number, number, number, number] {
  if (typeof value === "number") {
    const n = clampInt(value, 0, 0, 512);
    return [n, n, n, n];
  }
  if (Array.isArray(value) && value.length === 4) {
    return [clampInt(value[0], 0, 0, 512), clampInt(value[1], 0, 0, 512), clampInt(value[2], 0, 0, 512), clampInt(value[3], 0, 0, 512)];
  }
  return [0, 0, 0, 0];
}

function clampInt(value: unknown, fallback: number, min: number, max: number): number {
  const n = typeof value === "number" && Number.isFinite(value) ? Math.round(value) : fallback;
  return Math.min(max, Math.max(min, n));
}

/**
 * The chrome colours a skin overrides, or null if it overrides none.
 *
 * Only `UiTokens` — the keys are taken from the default theme's `ui` block, so
 * a manifest cannot smuggle a terminal colour in here under a `ui` name and
 * cannot invent a token. Each is checked as a colour, since it lands on the
 * root element as the value of a property the whole window reads.
 */
export function adoptColors(value: unknown): Partial<UiTokens> | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!raw || typeof raw !== "object") return null;
  const out: Partial<UiTokens> = {};
  let any = false;
  for (const token of Object.keys(themeFor(null).ui) as (keyof UiTokens)[]) {
    const c = colour(raw[token]);
    if (c === null) continue;
    out[token] = c;
    any = true;
  }
  return any ? out : null;
}

/**
 * The icon strip, or null. Fourteen cells across and one tall — the count is
 * `ICON_NAMES.length` and the stylesheet cuts the strip by it, so a picture of
 * any other proportion would put the wrong drawing on every button. Measured
 * where it can be; where it cannot, the shape is the author's problem and the
 * studio shows them.
 */
export function adoptIconSheet(
  value: unknown,
  asset: (file: string) => string | null,
  measure: (file: string) => [number, number] | null,
): IconSheet | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isAssetName(raw.image)) return null;
  const src = asset(raw.image);
  if (!src) return null;
  const size = measure(raw.image);
  if (size && size[0] !== size[1] * ICON_NAMES.length) return null;
  return { src, mode: raw.mode === "image" ? "image" : "mask" };
}

/**
 * A mascot manifest, made into the config kururu already understands.
 *
 * The sheet is named by the *installer*, not by the manifest: the file lands in
 * `~/.config/kururu/sheets` under the entry's id, and passing that in is what
 * keeps this from being a second opinion about where a file went. Everything
 * else is `adoptMascot`'s, verbatim — the clamping, the trim, the nullable idle
 * — because a mascot from the registry and a mascot somebody dragged out in
 * Settings are the same object and there is no reason for two adopters to
 * disagree about what a legal one is.
 */
export function adoptMascotManifest(value: unknown, sheet: string): MascotConfig {
  const raw = (value ?? {}) as Record<string, unknown>;
  return adoptMascot({ ...raw, sheet });
}

// ---------------------------------------------------------------------------
// Sounds
// ---------------------------------------------------------------------------

/**
 * The audio formats a style may ship.
 *
 * Narrower than what `server/src/sounds.ts` will *play*, and narrower on
 * purpose. That module's job is to offer whatever is already on the machine,
 * including the AIFF every macOS alert sound is, which it transcodes on the way
 * out with `afconvert`. A registry entry is the opposite case: it is a file
 * chosen by its author, downloaded to every machine kururu runs on, and played
 * by a phone as often as by the desktop. So it must be something every browser
 * decodes *without help* — a Linux box has no `afconvert`, and a format that
 * needed one would be an entry that is silence on half the machines that
 * installed it, which is the exact failure `sounds.ts` exists to prevent
 * arriving by another door.
 *
 * Three rather than the whole playable list: Ogg and Opus are refused because
 * `decodeAudioData` on iOS is not reliable about them, and the phone is the
 * client this feature is most for.
 */
export const SOUND_FORMATS: readonly string[] = [".wav", ".mp3", ".m4a"];

export function isSoundFile(value: unknown): value is string {
  return isAssetName(value) && SOUND_FORMATS.includes(value.slice(value.lastIndexOf(".")).toLowerCase());
}

/**
 * A sound manifest: an id, a name, and the one file it is.
 *
 * The thinnest of the five adopters, and it has nothing to merge or fall back
 * to because a sound is not a set of tokens — it is a file, and a file either
 * arrived or did not. What it does have is the same two-sided name check every
 * other asset gets: the manifest names a file, `install` records what actually
 * landed, and `server/src/sounds.ts` resolves the id against that record rather
 * than pasting it into a path.
 *
 * Deliberately *not* returned as anything playable. A theme becomes a `Theme`
 * and a skin becomes a `Skin` because the client draws them; a sound is bytes
 * the client fetches by id, so the only thing worth adopting is which file the
 * id means.
 */
export function adoptSoundManifest(value: unknown): { id: string; name: string; file: string } | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isStyleId(raw.id)) return null;
  if (!isSoundFile(raw.file)) return null;
  return { id: raw.id, name: line(raw.name) || raw.id, file: raw.file };
}

// ---------------------------------------------------------------------------
// Packs
// ---------------------------------------------------------------------------

/**
 * The parts a pack names, in the order they are installed and worn.
 *
 * A list rather than four fields spelled out at each call site, because there
 * are three of those — installing the parts, wearing them, and drawing the row
 * of thumbnails on the pack's card — and the one time they disagreed about
 * whether a pack had a sound was the day sounds landed.
 *
 * `theme` first and `sound` last is not arbitrary either: it is loudest to
 * quietest, so a pack half-installed over a bad connection has left you with the
 * colours rather than with a notification noise and nothing to look at.
 */
export type PackPart = "theme" | "skin" | "mascot" | "sound";

export const PACK_PARTS: readonly PackPart[] = ["theme", "skin", "mascot", "sound"];

/**
 * A pack, adopted: four ids and a face.
 *
 * Every part is optional — `null` for one a pack does not name — because a pack
 * is a *recommendation*, and one that only has an opinion about the palette and
 * the noise is a legitimate pack. `PACK_PARTS` predates sounds, so every pack
 * published before them has a null there and nothing downstream may assume
 * otherwise.
 *
 * ## Why the font is here and is not a part
 *
 * Because it is not an entry in the registry and cannot be: kururu does not
 * install fonts and should not — a typeface is a licence and a hundred kilobytes
 * per weight, and the one place it has to exist is the machine that draws the
 * glyphs, which on a phone over Tailscale is not the machine the agents are on.
 * So a pack *names* a face and that is all. A machine that has it wears it; a
 * machine that does not keeps the font it had, which is the same thing that
 * happens when somebody types a name into the box in Settings and is the reason
 * `web/src/fonts.ts` offers a list rather than validating one.
 *
 * It goes through `adoptFontFamily` rather than `line()` because the string ends
 * up in a CSS `font-family` on a window reachable from the tailnet, and a
 * manifest is exactly the untrusted file that adopter was written against.
 */
export interface PackManifest extends Record<PackPart, string | null> {
  id: string;
  name: string;
  /** A single family name, or `""` for a pack with no opinion about type. */
  font: string;
}

export function adoptPackManifest(value: unknown): PackManifest | null {
  const raw = (value ?? {}) as Record<string, unknown>;
  if (!isStyleId(raw.id)) return null;
  const part = (name: PackPart) => (isStyleId(raw[name]) ? (raw[name] as string) : null);
  return {
    id: raw.id,
    name: line(raw.name) || raw.id,
    theme: part("theme"),
    skin: part("skin"),
    mascot: part("mascot"),
    sound: part("sound"),
    font: adoptFontFamily(raw.font),
  };
}
