/**
 * A QR code, encoded here rather than fetched from somewhere.
 *
 * Kururu needs exactly one of these: a short `http://host:port` for a phone to
 * point at. That is the smallest job this format has — a couple of dozen bytes,
 * one error-correction level, a version in the low single digits — and the
 * libraries that do it are written for the general case, which is forty
 * versions, four correction levels, four encoding modes and a canvas renderer
 * nobody here wants. The whole of what is below is the byte-mode path, and it
 * is smaller than the dependency would have been.
 *
 * The output is a matrix of booleans and nothing else. No canvas, no data URI,
 * no quiet zone: the quiet zone is four modules of *margin*, which is a thing an
 * SVG viewBox says in one number, and baking it into the matrix would make every
 * consumer carry it whether it wanted it or not. `Reach.tsx` draws the matrix.
 *
 * Level M, and only level M. The four correction levels differ by how much of
 * the code you may obscure — 7%, 15%, 25%, 30% — and the trade is size: a URL
 * at L is a version smaller than the same URL at H, so the modules are bigger
 * and the scan is easier. Nothing is ever going to be printed, folded, or stuck
 * on a wall; it is on a screen eighteen inches from the camera, undamaged, and
 * the failure mode that actually happens there is modules too small to resolve.
 * M is the standard default and leaves the code small. Adding the other three
 * would mean the full tables for all of them, to serve a choice nobody making a
 * QR code of a LAN address has any way to reason about.
 *
 * The algorithm is ISO/IEC 18004 and follows Nayuki's reference structure,
 * which is the clearest published statement of it. `web/test/qr.test.ts` checks
 * the whole matrix, module for module, against codes generated by a separate
 * implementation — because every step here is a table or a polynomial, and a
 * wrong digit in either produces a picture that looks exactly like a QR code
 * and scans as nothing at all.
 */

/** Versions 1–10 only: the largest holds 213 bytes at level M, and a URL is 30. */
const MAX_VERSION = 10;

/** ECC codewords per block, level M, indexed by version − 1. */
const ECC_PER_BLOCK = [10, 16, 26, 18, 24, 16, 18, 22, 22, 26];
/** How many blocks the data is split into, level M, indexed by version − 1. */
const ECC_BLOCKS = [1, 1, 1, 2, 2, 4, 4, 4, 5, 5];

/**
 * The five format bits are the correction level and the mask; `00` is level M.
 * Not in the order you would guess — the levels are numbered L=1, M=0, Q=3, H=2
 * in the bitstream — which is the sort of thing that is worth writing down once
 * rather than rediscovering from a code that will not scan.
 */
const FORMAT_LEVEL_M = 0;

const PENALTY_N1 = 3;
const PENALTY_N2 = 3;
const PENALTY_N3 = 40;
const PENALTY_N4 = 10;

/**
 * The code for this text, as `matrix[y][x]`, true where a module is dark.
 *
 * Throws when the text does not fit in version 10, which for kururu means
 * somebody has handed a URL of more than 213 bytes to a thing whose entire
 * purpose is to be read by a camera. A silent truncation would produce a code
 * that scans perfectly and points at the wrong place.
 */
export function qrMatrix(text: string): boolean[][] {
  const data = new TextEncoder().encode(text);
  const version = versionFor(data.length);
  const codewords = interleave(encode(data, version), version);

  const size = version * 4 + 17;
  const modules = grid(size);
  /**
   * Which cells belong to the finders, timing, alignment and format areas. Kept
   * beside the matrix rather than derived from it, because a function module
   * that happens to be light is indistinguishable from an unwritten one, and the
   * data placement and the mask both have to skip them.
   */
  const reserved = grid(size);

  drawFunctionPatterns(modules, reserved, version);
  drawCodewords(modules, reserved, codewords);

  // Every mask is legal; the standard says to draw all eight and keep the one
  // that scores worst under the penalty rules, which is what the rules are for.
  // They punish the shapes a decoder can mistake for a finder pattern, so this
  // is not an aesthetic choice and cannot be replaced by picking a fixed mask.
  let best: boolean[][] | null = null;
  let bestPenalty = Infinity;
  for (let mask = 0; mask < 8; mask++) {
    const candidate = modules.map((row) => row.slice());
    applyMask(candidate, reserved, mask);
    drawFormatBits(candidate, mask);
    const score = penalty(candidate);
    if (score < bestPenalty) {
      bestPenalty = score;
      best = candidate;
    }
  }
  return best!;
}

function grid(size: number): boolean[][] {
  return Array.from({ length: size }, () => new Array<boolean>(size).fill(false));
}

// ---------------------------------------------------------------------------
// Capacity and the bitstream
// ---------------------------------------------------------------------------

/**
 * How many modules a version has to spend on data and error correction, once
 * the finders, timing and format areas are taken out.
 *
 * A closed form rather than a table of forty numbers. The three corrections are
 * the alignment patterns (which overlap the timing rows, hence the second-degree
 * term), and the two six-by-three version blocks that appear from version 7.
 */
function rawDataModules(version: number): number {
  let result = (16 * version + 128) * version + 64;
  if (version >= 2) {
    const alignments = Math.floor(version / 7) + 2;
    result -= (25 * alignments - 10) * alignments - 55;
    if (version >= 7) result -= 36;
  }
  return result;
}

/** Codewords a version carries in total, error correction included. */
function rawCodewords(version: number): number {
  return Math.floor(rawDataModules(version) / 8);
}

/** Codewords left for the message once error correction has taken its share. */
function dataCapacity(version: number): number {
  return rawCodewords(version) - ECC_PER_BLOCK[version - 1]! * ECC_BLOCKS[version - 1]!;
}

/** The smallest version this many bytes fit in. */
function versionFor(bytes: number): number {
  for (let version = 1; version <= MAX_VERSION; version++) {
    // Four bits of mode, then the length — eight bits up to version 9, sixteen
    // from version 10, which is the one discontinuity in byte mode.
    const header = 4 + (version < 10 ? 8 : 16);
    if (header + bytes * 8 <= dataCapacity(version) * 8) return version;
  }
  throw new Error(`qr: ${bytes} bytes will not fit in version ${MAX_VERSION}`);
}

/** Mode, length, payload, terminator, padding — the message as codewords. */
function encode(data: Uint8Array, version: number): number[] {
  const capacity = dataCapacity(version);
  const bits: number[] = [];
  const push = (value: number, width: number) => {
    for (let i = width - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };

  push(0b0100, 4); // byte mode
  push(data.length, version < 10 ? 8 : 16);
  for (const byte of data) push(byte, 8);

  // The terminator is up to four zero bits, and fewer when the capacity is
  // nearly reached — it marks the end of the message, so running past the end
  // to write it would be worse than leaving it short.
  push(0, Math.min(4, capacity * 8 - bits.length));
  push(0, (8 - (bits.length % 8)) % 8);

  const codewords: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j]!;
    codewords.push(byte);
  }
  // The two pad bytes the standard names, alternating. They are not arbitrary:
  // a decoder reading past the terminator has to find something that cannot be
  // mistaken for the start of another segment.
  for (let pad = 0xec; codewords.length < capacity; pad ^= 0xec ^ 0x11) codewords.push(pad);
  return codewords;
}

// ---------------------------------------------------------------------------
// Reed–Solomon
// ---------------------------------------------------------------------------

/** Multiply in GF(256) modulo the QR field's primitive polynomial, x⁸+x⁴+x³+x²+1. */
function fieldMultiply(x: number, y: number): number {
  let z = 0;
  for (let i = 7; i >= 0; i--) {
    z = (z << 1) ^ ((z >>> 7) * 0x11d);
    z ^= ((y >>> i) & 1) * x;
  }
  return z;
}

/** The generator polynomial of the given degree, as coefficients. */
function divisor(degree: number): number[] {
  const result = new Array<number>(degree).fill(0);
  result[degree - 1] = 1;
  let root = 1;
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      result[j] = fieldMultiply(result[j]!, root);
      if (j + 1 < degree) result[j] = result[j]! ^ result[j + 1]!;
    }
    root = fieldMultiply(root, 2);
  }
  return result;
}

/** The error-correction codewords for one block. */
function remainder(data: number[], gen: number[]): number[] {
  const result = new Array<number>(gen.length).fill(0);
  for (const byte of data) {
    const factor = byte ^ result.shift()!;
    result.push(0);
    for (let i = 0; i < gen.length; i++) result[i] = result[i]! ^ fieldMultiply(gen[i]!, factor);
  }
  return result;
}

/**
 * Split into blocks, correct each, then interleave.
 *
 * The interleaving is the point of the exercise and is easy to read as busywork:
 * a scratch or a thumb covers a *contiguous* area of the code, so laying the
 * blocks out one after another would put a whole block under it and exceed what
 * that block can recover. Spreading them byte by byte turns one big local loss
 * into a small loss in every block, which is the case the correction is sized
 * for. The blocks are not all the same length, so the shorter ones simply have
 * nothing to contribute on the last data pass.
 */
function interleave(data: number[], version: number): number[] {
  const blocks = ECC_BLOCKS[version - 1]!;
  const eccLength = ECC_PER_BLOCK[version - 1]!;
  const total = rawCodewords(version);
  const shortBlocks = blocks - (total % blocks);
  const shortLength = Math.floor(total / blocks);

  const gen = divisor(eccLength);
  const dataBlocks: number[][] = [];
  const eccBlocks: number[][] = [];
  let at = 0;
  for (let i = 0; i < blocks; i++) {
    const length = shortLength - eccLength + (i < shortBlocks ? 0 : 1);
    const block = data.slice(at, at + length);
    at += length;
    dataBlocks.push(block);
    eccBlocks.push(remainder(block, gen));
  }

  const result: number[] = [];
  for (let i = 0; i < shortLength - eccLength + 1; i++) {
    for (const block of dataBlocks) if (i < block.length) result.push(block[i]!);
  }
  for (let i = 0; i < eccLength; i++) {
    for (const block of eccBlocks) result.push(block[i]!);
  }
  return result;
}

// ---------------------------------------------------------------------------
// The picture
// ---------------------------------------------------------------------------

function drawFunctionPatterns(modules: boolean[][], reserved: boolean[][], version: number): void {
  const size = modules.length;
  const set = (x: number, y: number, dark: boolean) => {
    if (x < 0 || y < 0 || x >= size || y >= size) return;
    modules[y]![x] = dark;
    reserved[y]![x] = true;
  };

  // Timing: the alternating rows that tell a decoder how wide a module is.
  for (let i = 0; i < size; i++) {
    set(6, i, i % 2 === 0);
    set(i, 6, i % 2 === 0);
  }

  // The three finders, and the light separator around each — drawn as one
  // nine-by-nine block per corner, since a ring at distance 2 or 4 from the
  // centre is exactly the separator and the gap.
  for (const [cx, cy] of [[3, 3], [size - 4, 3], [3, size - 4]] as const) {
    for (let dy = -4; dy <= 4; dy++) {
      for (let dx = -4; dx <= 4; dx++) {
        const distance = Math.max(Math.abs(dx), Math.abs(dy));
        set(cx + dx, cy + dy, distance !== 2 && distance !== 4);
      }
    }
  }

  // Alignment patterns at every crossing of the position list, except the three
  // that would land on a finder.
  const positions = alignmentPositions(version);
  for (let i = 0; i < positions.length; i++) {
    for (let j = 0; j < positions.length; j++) {
      const corner =
        (i === 0 && j === 0) ||
        (i === 0 && j === positions.length - 1) ||
        (i === positions.length - 1 && j === 0);
      if (corner) continue;
      for (let dy = -2; dy <= 2; dy++) {
        for (let dx = -2; dx <= 2; dx++) {
          set(positions[i]! + dx, positions[j]! + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1);
        }
      }
    }
  }

  // Reserve the format area by drawing it once with a mask that will be drawn
  // over later. Reserving and drawing are the same gesture here, and doing them
  // separately is how a data codeword ends up written into the format strip.
  drawFormatBits(modules, 0, reserved);
  if (version >= 7) drawVersionBits(modules, reserved, version);
}

/**
 * Where the alignment patterns sit, derived rather than tabulated.
 *
 * They are evenly spaced between 6 and size − 7, with the *first* gap allowed to
 * be the odd one out — which is why this walks backwards from the far edge and
 * inserts, rather than stepping forward from 6.
 */
function alignmentPositions(version: number): number[] {
  if (version === 1) return [];
  const count = Math.floor(version / 7) + 2;
  const step = Math.ceil((version * 4 + 4) / (count * 2 - 2)) * 2;
  const result = [6];
  for (let pos = version * 4 + 17 - 7; result.length < count; pos -= step) result.splice(1, 0, pos);
  return result;
}

/**
 * The fifteen format bits, twice — once around the top-left finder and once
 * split between the other two. Two copies because they are the one thing a
 * decoder must read before it can read anything else: lose them and the code is
 * not damaged, it is unreadable.
 */
function drawFormatBits(modules: boolean[][], mask: number, reserved?: boolean[][]): void {
  const size = modules.length;
  const set = (x: number, y: number, dark: boolean) => {
    modules[y]![x] = dark;
    if (reserved) reserved[y]![x] = true;
  };

  const data = (FORMAT_LEVEL_M << 3) | mask;
  let rem = data;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  const bits = (((data << 10) | rem) ^ 0x5412) >>> 0;
  const bit = (i: number) => ((bits >>> i) & 1) !== 0;

  for (let i = 0; i <= 5; i++) set(8, i, bit(i));
  set(8, 7, bit(6));
  set(8, 8, bit(7));
  set(7, 8, bit(8));
  for (let i = 9; i < 15; i++) set(14 - i, 8, bit(i));

  for (let i = 0; i < 8; i++) set(size - 1 - i, 8, bit(i));
  for (let i = 8; i < 15; i++) set(8, size - 15 + i, bit(i));
  // The one module that is always dark, and has no meaning beyond being so.
  set(8, size - 8, true);
}

/** The eighteen version bits, from version 7 up, beside the two far finders. */
function drawVersionBits(modules: boolean[][], reserved: boolean[][], version: number): void {
  const size = modules.length;
  let rem = version;
  for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25);
  const bits = ((version << 12) | rem) >>> 0;
  for (let i = 0; i < 18; i++) {
    const dark = ((bits >>> i) & 1) !== 0;
    const a = size - 11 + (i % 3);
    const b = Math.floor(i / 3);
    modules[b]![a] = dark;
    reserved[b]![a] = true;
    modules[a]![b] = dark;
    reserved[a]![b] = true;
  }
}

/**
 * The message, written in a zigzag of two-column strips from the bottom-right
 * corner leftwards, skipping whatever the function patterns have already taken.
 *
 * Column 6 is stepped over wholesale: it is the vertical timing line, so a strip
 * that included it would be one column wide and the pairing would break for
 * everything to its left.
 */
function drawCodewords(modules: boolean[][], reserved: boolean[][], codewords: number[]): void {
  const size = modules.length;
  let i = 0;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    for (let vertical = 0; vertical < size; vertical++) {
      for (let j = 0; j < 2; j++) {
        const x = right - j;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? size - 1 - vertical : vertical;
        if (reserved[y]![x] || i >= codewords.length * 8) continue;
        modules[y]![x] = ((codewords[i >>> 3]! >>> (7 - (i & 7))) & 1) !== 0;
        i++;
      }
    }
  }
}

/**
 * Invert every data module the mask selects.
 *
 * The masks exist because the message is arbitrary and a run of zero bytes would
 * otherwise draw a large blank field, which a camera cannot find the edges of.
 * Each is a cheap function of the coordinates so that a decoder can undo it
 * knowing only which one was used, which is what the format bits carry.
 */
function applyMask(modules: boolean[][], reserved: boolean[][], mask: number): void {
  const size = modules.length;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      if (reserved[y]![x]) continue;
      if (maskAt(mask, x, y)) modules[y]![x] = !modules[y]![x];
    }
  }
}

function maskAt(mask: number, x: number, y: number): boolean {
  switch (mask) {
    case 0: return (x + y) % 2 === 0;
    case 1: return y % 2 === 0;
    case 2: return x % 3 === 0;
    case 3: return (x + y) % 3 === 0;
    case 4: return (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0;
    case 5: return ((x * y) % 2) + ((x * y) % 3) === 0;
    case 6: return (((x * y) % 2) + ((x * y) % 3)) % 2 === 0;
    default: return (((x + y) % 2) + ((x * y) % 3)) % 2 === 0;
  }
}

/**
 * How bad a masked code is, by the standard's four rules: long runs of one
 * colour, solid two-by-two blocks, anything resembling a finder pattern, and an
 * imbalance between dark and light. Lower is better and the absolute number
 * means nothing — it exists only to be compared against the other seven masks.
 */
function penalty(modules: boolean[][]): number {
  const size = modules.length;
  let result = 0;

  for (const axis of [0, 1]) {
    for (let major = 0; major < size; major++) {
      let runColor = false;
      let runLength = 0;
      const history = [0, 0, 0, 0, 0, 0, 0];
      for (let minor = 0; minor < size; minor++) {
        const dark = axis === 0 ? modules[major]![minor]! : modules[minor]![major]!;
        if (dark === runColor) {
          runLength++;
          if (runLength === 5) result += PENALTY_N1;
          else if (runLength > 5) result++;
        } else {
          pushRun(history, runLength, size);
          if (!runColor) result += finderLikeRuns(history) * PENALTY_N3;
          runColor = dark;
          runLength = 1;
        }
      }
      result += terminateRuns(history, runColor, runLength, size) * PENALTY_N3;
    }
  }

  for (let y = 0; y < size - 1; y++) {
    for (let x = 0; x < size - 1; x++) {
      const dark = modules[y]![x]!;
      if (dark === modules[y]![x + 1] && dark === modules[y + 1]![x] && dark === modules[y + 1]![x + 1]) {
        result += PENALTY_N2;
      }
    }
  }

  let dark = 0;
  for (const row of modules) for (const cell of row) if (cell) dark++;
  const total = size * size;
  // How many whole five-percent steps the dark proportion is away from half.
  result += (Math.ceil(Math.abs(dark * 20 - total * 10) / total) - 1) * PENALTY_N4;
  return result;
}

/**
 * Remember one run's length. The first run of a line gets the quiet zone added
 * to it, because the border really is light modules and the 1:1:3:1:1 pattern
 * that rule three looks for is allowed to lean on it.
 */
function pushRun(history: number[], length: number, size: number): void {
  if (history[0] === 0) length += size;
  history.pop();
  history.unshift(length);
}

/** How many of the last seven runs read as a finder pattern with its gap. */
function finderLikeRuns(history: number[]): number {
  const n = history[1]!;
  const core =
    n > 0 && history[2] === n && history[3] === n * 3 && history[4] === n && history[5] === n;
  return (
    (core && history[0]! >= n * 4 && history[6]! >= n ? 1 : 0) +
    (core && history[6]! >= n * 4 && history[0]! >= n ? 1 : 0)
  );
}

/** The same, for the run a line ends on, with the trailing quiet zone counted. */
function terminateRuns(history: number[], runColor: boolean, runLength: number, size: number): number {
  if (runColor) {
    pushRun(history, runLength, size);
    runLength = 0;
  }
  pushRun(history, runLength + size, size);
  return finderLikeRuns(history);
}
